### PR TITLE
Format Python source

### PR DESCRIPTION
**Pull request by srstevenson**
This was achieved using `black --line-length 79 --skip-string-normalization`, to best match the existing conventional code style (lines fewer than 80 characters long, and single quoted rather than double quoted strings), whilst ensuring formatting consistency.

### CODE REVIEW

**Comment by pbugnion** [comment]
Thanks for this. 

Somewhat annoyingly, by removing trailing whitespaces in a string literal, this has broken the tests. When you print a table, any content in the last column has to be right-padded so the column has the same width.

**Comment by pbugnion** [comment]
Separately, I'm not wedded to single quotes. I'm happy to switch to double quotes for consistency with other ASI projects.

**Comment by srstevenson** [comment]
@pbugnion PTAL: I've made the tests not dependent on the trailing whitespace in the manner you suggested, and also converted from single to double quoted strings.

**Comment by janfreyberg** [comment]
My only request would be to add format checks to the travis job, but that's something that can be done later

**Comment by srstevenson** [comment]
> @srstevenson Public transport accessibility level?

["Please take a(nother) look."](https://github.com/golang/go/wiki/CodeReview#reviewer-parlance)

**Comment by srstevenson** [comment]
> My only request would be to add format checks to the travis job, but that's something that can be done later

Agreed, I'll submit an additional PR to add a formatting check to the Travis CI build.

**Pull request merged**
